AWSTemplateFormatVersion: 2010-09-09
Description: "Mystery Shopper ETL pipeline example for AWS week in the Data Engineering\
  \ Software Academy\n"
Parameters:
  YourName:
    Type: String
    Description: Enter your name in format 'first-last' to customise the way 
      your resources are named
  NetworkStackName:
    Type: String
    Default: project-networking
    Description: Network stack with VPC containing Redshift instance
Resources:
  EtlLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: ${YourName}-shopper-etl-lambda
      Runtime: python3.12
      Handler: mystery_shop_etl_lambda.lambda_handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role
      Timeout: 30
      ReservedConcurrentExecutions: 10
      Code:
        S3Bucket: sarah-smith-shopper-deployment-bucket
        S3Key: 7053cdf9c220c19d8b0f26e64aa3ef78
      VpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackName}-VPCSGID
        SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackName}-PrivateSubnet0ID
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${YourName}-shopper-etl-lambda
  ShopperRawDataBucket:
    Type: AWS::S3::Bucket
    DependsOn:
    - ShopperRawDataBucketPermission
    - EtlLambdaFunction
    Properties:
      BucketName:
        Fn::Sub: ${YourName}-shopper-raw-data
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function:
            Fn::GetAtt:
            - EtlLambdaFunction
            - Arn
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${YourName}-shopper-raw-data
  ShopperRawDataBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: EtlLambdaFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${YourName}-shopper-raw-data
  ShopperRawDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ShopperRawDataBucket
      PolicyDocument:
        Statement:
        - Sid: AllowSSLRequestsOnly
          Action: s3:*
          Principal: '*'
          Effect: Deny
          Resource:
          - Fn::Sub: arn:aws:s3:::${YourName}-shopper-raw-data
          - Fn::Sub: arn:aws:s3:::${YourName}-shopper-raw-data/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
